// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtRvx4tGfx7Afutc4vNukDOITucg_IQP8',
    appId: '1:591719479365:web:31d72d81b09ad74fd5cb2c',
    messagingSenderId: '591719479365',
    projectId: 'fcmnewst',
    authDomain: 'fcmnewst.firebaseapp.com',
    storageBucket: 'fcmnewst.appspot.com',
    measurementId: 'G-N505T65NJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1eghe_1PX5vcpOcP9pdmNn0VPZFj1Bz0',
    appId: '1:591719479365:android:eefe703822e71da0d5cb2c',
    messagingSenderId: '591719479365',
    projectId: 'fcmnewst',
    storageBucket: 'fcmnewst.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVZLDpNssI8c500kBwSJZEkg7GiNxEXwg',
    appId: '1:591719479365:ios:6f58577cf2f07d96d5cb2c',
    messagingSenderId: '591719479365',
    projectId: 'fcmnewst',
    storageBucket: 'fcmnewst.appspot.com',
    iosBundleId: 'com.example.fcmyoutube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVZLDpNssI8c500kBwSJZEkg7GiNxEXwg',
    appId: '1:591719479365:ios:6f58577cf2f07d96d5cb2c',
    messagingSenderId: '591719479365',
    projectId: 'fcmnewst',
    storageBucket: 'fcmnewst.appspot.com',
    iosBundleId: 'com.example.fcmyoutube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtRvx4tGfx7Afutc4vNukDOITucg_IQP8',
    appId: '1:591719479365:web:88523966e599ef03d5cb2c',
    messagingSenderId: '591719479365',
    projectId: 'fcmnewst',
    authDomain: 'fcmnewst.firebaseapp.com',
    storageBucket: 'fcmnewst.appspot.com',
    measurementId: 'G-B9E0TB528R',
  );
}
